name: enigma_vis
channels:
  - defaults
  - conda-forge
dependencies:
  - anyio=3.5.0
  - appdirs=1.4.4
  - appnope=0.1.2
  - argon2-cffi=21.3.0
  - argon2-cffi-bindings=21.2.0
  - asttokens=2.0.5
  - attrs=22.1.0
  - babel=2.11.0
  - backcall=0.2.0
  - beautifulsoup4=4.11.1
  - blas=2.116
  - blas-devel=3.9.0
  - bleach=4.1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotlipy=0.7.0
  - bzip2=1.0.8
  - c-ares=1.18.1
  - ca-certificates=2023.01.10
  - certifi=2022.12.7
  - cffi=1.15.1
  - charset-normalizer=2.0.4
  - comm=0.1.2
  - cryptography=39.0.1
  - curl=7.88.1
  - debugpy=1.5.1
  - decorator=5.1.1
  - defusedxml=0.7.1
  - double-conversion=3.1.5
  - eigen=3.3.7
  - entrypoints=0.4
  - executing=0.8.3
  - expat=2.4.9
  - ffmpeg=4.2.2
  - flit-core=3.6.0
  - freetype=2.12.1
  - gettext=0.21.0
  - giflib=5.2.1
  - gl2ps=1.4.2
  - glew=2.1.0
  - glib=2.69.1
  - gmp=6.2.1
  - gnutls=3.6.15
  - gst-plugins-base=1.14.1
  - gstreamer=1.14.1
  - hdf4=4.2.13
  - hdf5=1.12.1
  - icu=68.1
  - idna=3.4
  - importlib-metadata=4.11.3
  - importlib_resources=5.2.0
  - ipykernel=6.19.2
  - ipython=8.10.0
  - ipython_genutils=0.2.0
  - ipywidgets=8.0.0
  - jedi=0.18.1
  - jinja2=3.1.2
  - jpeg=9e
  - json5=0.9.6
  - jsoncpp=1.9.4
  - jsonschema=4.17.3
  - jupyter=1.0.0
  - jupyter_client=7.4.9
  - jupyter_console=6.6.2
  - jupyter_core=5.2.0
  - jupyter_server=1.23.4
  - jupyterlab=3.5.3
  - jupyterlab_pygments=0.1.2
  - jupyterlab_server=2.19.0
  - jupyterlab_widgets=3.0.5
  - krb5=1.19.4
  - lame=3.100
  - lcms2=2.12
  - lerc=3.0
  - libblas=3.9.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libcblas=3.9.0
  - libclang=12.0.0
  - libcurl=7.88.1
  - libcxx=14.0.6
  - libdeflate=1.17
  - libedit=3.1.20221030
  - libev=4.33
  - libffi=3.4.2
  - libgfortran=5.0.0
  - libgfortran5=11.3.0
  - libiconv=1.16
  - libidn2=2.3.1
  - liblapack=3.9.0
  - liblapacke=3.9.0
  - libllvm12=12.0.0
  - libnetcdf=4.8.1
  - libnghttp2=1.46.0
  - libogg=1.3.5
  - libopenblas=0.3.21
  - libopus=1.3
  - libpng=1.6.39
  - libpq=12.9
  - libsodium=1.0.18
  - libssh2=1.10.0
  - libtasn1=4.16.0
  - libtheora=1.1.1
  - libtiff=4.5.0
  - libunistring=0.9.10
  - libvorbis=1.3.7
  - libvpx=1.10.0
  - libwebp=1.2.4
  - libwebp-base=1.2.4
  - libxml2=2.9.14
  - libxslt=1.1.35
  - libzip=1.8.0
  - llvm-openmp=14.0.6
  - loguru=0.5.3
  - lxml=4.9.1
  - lz4-c=1.9.4
  - markupsafe=2.1.1
  - matplotlib-base=3.7.0
  - matplotlib-inline=0.1.6
  - mistune=0.8.4
  - munkres=1.1.4
  - nbclassic=0.5.2
  - nbclient=0.5.13
  - nbconvert=6.5.4
  - nbformat=5.7.0
  - ncurses=6.4
  - nest-asyncio=1.5.6
  - nettle=3.7.3
  - notebook=6.5.2
  - notebook-shim=0.2.2
  - nspr=4.33
  - nss=3.74
  - numexpr=2.8.4
  - numpy-base=1.23.5
  - openblas=0.3.21
  - openh264=1.8.0
  - openssl=1.1.1t
  - pandocfilters=1.5.0
  - parso=0.8.3
  - patsy=0.5.3
  - pcre=8.45
  - pexpect=4.8.0
  - pickleshare=0.7.5
  - pip=23.0.1
  - platformdirs=2.5.2
  - ply=3.11
  - pooch=1.4.0
  - proj=7.2.0
  - prometheus_client=0.14.1
  - prompt-toolkit=3.0.36
  - prompt_toolkit=3.0.36
  - psutil=5.9.0
  - ptyprocess=0.7.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.11.2
  - pyopenssl=23.0.0
  - pyqt=5.15.7
  - pyqt5-sip=12.11.0
  - pyrsistent=0.18.0
  - pysocks=1.7.1
  - python=3.9.16
  - python-fastjsonschema=2.16.2
  - pyzmq=23.2.0
  - qt=5.15.9
  - qt-main=5.15.2
  - qt-webengine=5.15.9
  - qtconsole=5.4.0
  - qtpy=2.2.0
  - qtwebkit=5.212
  - readline=8.2
  - requests=2.28.1
  - seaborn=0.12.2
  - send2trash=1.8.0
  - setuptools=65.6.3
  - sip=6.6.2
  - sniffio=1.2.0
  - soupsieve=2.3.2.post1
  - sqlite=3.40.1
  - stack_data=0.2.0
  - statsmodels=0.13.5
  - tbb=2021.7.0
  - terminado=0.17.1
  - tinycss2=1.2.1
  - tk=8.6.12
  - toml=0.10.2
  - tomli=2.0.1
  - tornado=6.2
  - tqdm=4.65.0
  - traitlets=5.7.1
  - typing-extensions=4.4.0
  - typing_extensions=4.4.0
  - tzdata=2022g
  - urllib3=1.26.14
  - utfcpp=3.2.1
  - vtk=9.0.3
  - wcwidth=0.2.5
  - webencodings=0.5.1
  - websocket-client=0.58.0
  - wheel=0.38.4
  - widgetsnbextension=4.0.3
  - x264=1!152.20180806
  - xz=5.2.10
  - zeromq=4.3.4
  - zlib=1.2.13
  - zstd=1.5.2
  - pip:
      - bctpy==0.6.0
      - brainspace==0.1.10
      - contourpy==1.0.7
      - cycler==0.11.0
      - enigmatoolbox==2.0.3
      - fonttools==4.39.0
      - imageio==2.34.2
      - importlib-resources==5.12.0
      - joblib==1.2.0
      - kiwisolver==1.4.4
      - matplotlib==3.7.1
      - neuromaps==0.0.5
      - nibabel==5.0.1
      - nilearn==0.10.4
      - numpy==1.24.2
      - packaging==23.0
      - pandas==2.0.0rc0
      - pillow==9.4.0
      - pyparsing==3.1.0a1
      - python-dateutil==2.8.2
      - pytz==2022.7.1
      - scikit-learn==1.2.2
      - scipy==1.10.1
      - six==1.16.0
      - surfplot==0.2.0
      - threadpoolctl==3.1.0
      - zipp==3.15.0
